
# SEO settings
title: "Nicks_"
title2: "Blogspace" # default: ""
description: "Trying to be a miniamalist a technical writer."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace, GES, Alfred, Alfred Univeristy, Nick"
url: http://nickcanny.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

#google_analytics: UA-XXXXX-XX
repo: https://nickcanny.github.io/
#disqus_shortname: "hnbloggithub"
#twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Nick Cantafio"
  job      : "Manufacturing Engineer"
  bio      : "Glass engineer working in manufacturing with a interest in coding and travel."
  thumb    : /images/author.jpg
  email    : ntcnatafio@gmail.com
  url      : http://nickcanny.github.io
  github   : http://github.com/nickcanny
  #twitter  : http://twitter.com/HeiswayiNrird
  #facebook : https://www.facebook.com/heiswayi.nrird
  linkedin : http://linkedin.com/in/ntcantafio

# social settings
og_locale: "en_US"
#twitter_card: "summary_large_image"
#twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
